CREATE SCHEMA IF NOT EXISTS schema_emails;

CREATE TABLE IF NOT EXISTS schema_emails.emails
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT,
    time TEXT,
    "to" TEXT,
    subject TEXT,
    message TEXT
);

