CREATE SCHEMA IF NOT EXISTS schema_emails;


CREATE TABLE IF NOT EXISTS schema_emails.emails
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('instantSending', 'delayedSending')),
    time TEXT,
    "to" TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,

    CHECK (
        (type = 'instantSending' AND time IS NULL) OR
        (type = 'delayedSending' AND time IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_emails_to ON schema_emails.emails ("to");

